In [5]:
import pandas as pd
import numpy as np
import MDP

In [6]:
Fig[17,1] = GridMDP([[-0.04, -0.04, -0.04, +1],
                     [-0.04, None,  -0.04, -1],
                     [-0.04, -0.04, -0.04, -0.04]],
                    terminals=[(3, 2), (3, 1)])

NameError: name 'GridMDP' is not defined

**Defining the Variables**

In [34]:
states=np.array([[1,1],[1,2],[1,3],[2,1],[2,2],[2,3],[3,1],[3,2],[3,3],[4,1],[4,2],[4,3]])
rewards=np.array([-0.04, -0.04, -0.04, +1,-0.04, None, -0.04, -1,-0.04, -0.04, -0.04, -0.04]).reshape(4,3)
actions={'up','down','left','right'}
action_list=list(actions)

print(states)
print(rewards)
print(actions)
print(policy)

[[1 1]
 [1 2]
 [1 3]
 [2 1]
 [2 2]
 [2 3]
 [3 1]
 [3 2]
 [3 3]
 [4 1]
 [4 2]
 [4 3]]
[[-0.04 -0.04 -0.04]
 [1 -0.04 None]
 [-0.04 -1 -0.04]
 [-0.04 -0.04 -0.04]]
{'left', 'right', 'down', 'up'}
{}


In [35]:
# Create an empty dictionary called policy
policy = {}

# Iterate through the states
for state in states:

  # Randomly choose an action from the action_list
  action = action_list[np.random.randint(0, len(action_list))]

  # Add the state-action pair to the policy dictionary
  policy[tuple(state)] = action

# Print the policy
print(policy)

{(1, 1): 'down', (1, 2): 'right', (1, 3): 'down', (2, 1): 'right', (2, 2): 'left', (2, 3): 'left', (3, 1): 'left', (3, 2): 'down', (3, 3): 'left', (4, 1): 'down', (4, 2): 'down', (4, 3): 'right'}


In [38]:
transition_model = {}

for state in states:
  for action in actions:
    prob = 0.5
    next_state = state
    if action == 'up':
      next_state = (state[0], state[1] + 1)
    elif action == 'down':
      next_state = (state[0], state[1] - 1)
    elif action == 'left':
      next_state = (state[0] - 1, state[1])
    elif action == 'right':
      next_state = (state[0] + 1, state[1])

    transition_model[(state, action)] = [(prob, next_state)]

TypeError: unhashable type: 'numpy.ndarray'

FileNotFoundError: [Errno 2] No such file or directory: '../images/figure_3_2_linear_system.png'

In [14]:
from MDP import *
grid = [[-0.04, -0.04, -0.04, +1],
            [-0.04, None, -0.04, -1],
            [-0.04, -0.04, -0.04, -0.04]]
terminals = [(3, 2), (3, 1)]

mpd = GridMDP(grid, terminals)

U = value_iteration(mpd)
pi = best_policy(mpd, U)

print("Optimal Policy:")
print(pi)
GridMDP.display_policy_with_arrows(pi, mdp)
    

Optimal Policy:
{(0, 1): (0, 1), (1, 2): (1, 0), (2, 1): (0, 1), (0, 0): (0, 1), (3, 1): None, (2, 0): (0, 1), (3, 0): (-1, 0), (0, 2): (1, 0), (2, 2): (1, 0), (1, 0): (1, 0), (3, 2): None}


AttributeError: type object 'GridMDP' has no attribute 'display_policy_with_arrows'