In [1]:
import numpy as np

In [2]:
#python lists are heterogeneous
L3 = [True, "2", 3.0, 4]
print([type(item) for item in L3])

#python arrays little better - provides more efficient storage but not efficient operations on them
import array
L = list(range(10))
A = array.array('i', L); print(A)

#numpy arrays provide efficient array based storage as well as efficient operations - ufuncs, etc.
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

#BAD---->>>>>using list.append
import time
start = time.time()
for _ in range(10):
    my_list2=[]
    for e in my_list:
        my_list2.append(e*2)
elapsed_time = (time.time() - start)
#my_list2
print("t1 ",str(elapsed_time))


#BETTER----->>>>>>using list comprehension
import time
start = time.time()
for _ in range(10): my_list2 = [x * 2 for x in my_list]
elapsed_time = (time.time() - start)
#my_list2
print("t2 ",str(elapsed_time))

#BEST--------->>>>>>>>>>>>>>using numpy array
import time
start = time.time()
for _ in range(10): my_arr2 = my_arr * 2
elapsed_time = (time.time() - start)
#my_arr2
print("t3 ",str(elapsed_time))


[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
t1  2.0726940631866455
t2  1.0126888751983643
t3  0.03169679641723633


In [3]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
A*2

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
A+2

TypeError: can only append array (not "int") to array

In [8]:
A.append(10); A 

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [9]:
my_arr2 = np.arange(10); my_arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
print(my_arr2*2); print(my_arr2+2); my_arr2

[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.array([1, 4, 2, 5, 3]); print(arr)

#list to ndarray
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1); print(arr1)
print("--------")

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1,dtype=np.float128); print(arr1)
print(arr1.itemsize)
print(arr1.ndim)
print("--------")

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1,dtype='float64'); print(arr1)
print(arr1.itemsize)
print("--------")

#nested list to multidimensional ndarray
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2); print(arr2)
print(arr2.itemsize) # no. of bytes occupied by each item
print(arr2.ndim)  # no. of dimensions
print(arr2.nbytes)  # = size x itemsize
print(arr2.size) # like length i.e. total no. of items
print(arr2.shape) # dimensions

[1 4 2 5 3]
[ 6.   7.5  8.   0.   1. ]
--------
[ 6.0  7.5  8.0  0.0  1.0]
16
1
--------
[ 6.   7.5  8.   0.   1. ]
8
--------
[[1 2 3 4]
 [5 6 7 8]]
8
2
64
8
(2, 4)


In [12]:
import sys

In [13]:
L = list(range(1000))
A = array.array('i', L)
my_arr = np.arange(1000)
#print(A); print(L); print(my_arr)

In [14]:
sys.getsizeof(A)

4064

In [15]:
sys.getsizeof(L)

9112

In [16]:
sys.getsizeof(my_arr)

8096

In [17]:
my_arr.itemsize; print(my_arr.nbytes)

8000


In [18]:
my_arr.itemsize

8

In [19]:
np.array?

In [20]:
data = np.random.randn(2, 3); print(data)
print(data.shape,data.ndim,data.dtype,data.itemsize,data.size,data.nbytes)

#np.arange(10)
print(np.arange(2, 10, dtype=float))

[[ 1.64927616 -0.78869288 -2.30983042]
 [-1.18330771 -1.51386354 -0.48902406]]
(2, 3) 2 float64 8 6 48
[ 2.  3.  4.  5.  6.  7.  8.  9.]


In [21]:
?np.random.randn

In [22]:
#overflow and trucation errors
print(np.power(100, 8, dtype=np.int64))
print(np.power(100, 8, dtype=np.int32))
print(np.power(100, 100, dtype=np.int64))
print(np.power(100, 100, dtype=np.float64))
print(np.power(100, 100, dtype=np.float16))
#truncation happens here - CAREFUL!!!
arr11 = np.array([1.3,2.5], dtype=np.int16)
print(arr11)


10000000000000000
1874919424
0
1e+200
inf
[1 2]


/Users/sudeepmallick/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in power
  


In [23]:
#use of standard numpy functions to create arrays
print(np.zeros(10))
print(np.zeros((3, 6)))
#uninitialized garbage values
print(np.empty((2, 3, 2)))
#np.arange(15)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[  0.00000000e+000   9.38724727e-323]
  [  0.00000000e+000   4.94065646e-324]
  [  0.00000000e+000   5.74084147e+169]]

 [[  0.00000000e+000   1.45138931e+165]
  [  0.00000000e+000   1.56055729e+161]
  [  0.00000000e+000   4.04738577e-317]]]


In [24]:
print(np.zeros([2,3,2]))

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


In [25]:
print(np.arange(3,10,2))
print(np.arange(3,10,2,dtype='float'))
print(np.arange(3,10,2,dtype=np.float128))
print(np.arange(3,10,2,dtype=np.float64))

[3 5 7 9]
[ 3.  5.  7.  9.]
[ 3.0  5.0  7.0  9.0]
[ 3.  5.  7.  9.]


In [26]:
import numpy as np

In [27]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8],[5, 6, 7, 8]]
arr2 = np.array(data2); print(arr2); print(arr2.shape)
data2 = [[[1, 2, 3, 4], [5, 6, 7, 8],[5, 6, 7, 8]]]
arr2 = np.array(data2); print(arr2); print(arr2.shape)


[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
(3, 4)
[[[1 2 3 4]
  [5 6 7 8]
  [5 6 7 8]]]
(1, 3, 4)


In [28]:
arr14 = np.eye(3); print(arr14)
arr22 = np.linspace(3,100,12); print(arr22)
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[   3.           11.81818182   20.63636364   29.45454545   38.27272727
   47.09090909   55.90909091   64.72727273   73.54545455   82.36363636
   91.18181818  100.        ]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [29]:
#indexing of arrays - single index, slicing, boolean indexing, fancy indexing, multi-dimensional subarrays
arr12 = np.array([[2,3,4],[3,5,3]]); print(arr12)
#for multidimensional, dimensions are separated by commas
print(arr12[1,1]); print("====")
print(arr12[1,1].ndim)
print(arr12[1,1:]); print(arr12[1,1:].ndim)
print(arr12[:1, :2])
print(arr12[:1, :2].reshape(2,1)); print("----")
print(arr12[:1, :2].ndim)
print(arr12[:1, :2].shape)

[[2 3 4]
 [3 5 3]]
5
====
0
[5 3]
1
[[2 3]]
[[2]
 [3]]
----
2
(1, 2)


In [30]:
a = 1,1
type(a)

tuple

In [31]:
print(arr12[:,:2])
print(arr12[:1,:] )   #alternatively arr12[:1]
data1 = [6, 7.5, 8, 0, 1]; arr1 = np.array(data1)
print(arr1[2:-1])
arr16 = arr1[2:4]; print(arr16)

[[2 3]
 [3 5]]
[[2 3 4]]
[ 8.  0.]
[ 8.  0.]


In [32]:
#array indexing is a no copy operation
print(arr1)
arr16 = arr1[2:4]; print(arr16)
arr16[0]=100; print(arr1)
#getting a copy
arr16 = arr1[2:4].copy(); print(arr16)
arr16[0]=1000; print(arr16)
print(arr1)

[ 6.   7.5  8.   0.   1. ]
[ 8.  0.]
[   6.     7.5  100.     0.     1. ]
[ 100.    0.]
[ 1000.     0.]
[   6.     7.5  100.     0.     1. ]


In [33]:
#array reshaping
#row major arrangement (C-style)
arr22 = np.linspace(3,100,12); print(arr22)
arr22_reshaped = arr22.reshape(6,2); print(arr22_reshaped)

[   3.           11.81818182   20.63636364   29.45454545   38.27272727
   47.09090909   55.90909091   64.72727273   73.54545455   82.36363636
   91.18181818  100.        ]
[[   3.           11.81818182]
 [  20.63636364   29.45454545]
 [  38.27272727   47.09090909]
 [  55.90909091   64.72727273]
 [  73.54545455   82.36363636]
 [  91.18181818  100.        ]]


In [34]:
#column major arrangement (Fortran style)
arr22_reshaped = arr22.reshape(6,2,order='F'); print(arr22_reshaped)
print(arr22_reshaped[1:4:2,:])

[[   3.           55.90909091]
 [  11.81818182   64.72727273]
 [  20.63636364   73.54545455]
 [  29.45454545   82.36363636]
 [  38.27272727   91.18181818]
 [  47.09090909  100.        ]]
[[ 11.81818182  64.72727273]
 [ 29.45454545  82.36363636]]


In [35]:
x = np.array([1, 2, 3])
print(x)
print(x.ndim)
print(x.shape)
print("---")
y = x.reshape((1, 3)); print(y)
print(y.shape)
print(x.shape)
print("---")
y = x.reshape((3, 1)); print(y)
print(y.shape)
print(x.shape)
print("---")
y = x[np.newaxis, :]; print(y)
print(y.shape)
print("---")
y = x[:, np.newaxis]; print(y)
print(y.shape)

[1 2 3]
1
(3,)
---
[[1 2 3]]
(1, 3)
(3,)
---
[[1]
 [2]
 [3]]
(3, 1)
(3,)
---
[[1 2 3]]
(1, 3)
---
[[1]
 [2]
 [3]]
(3, 1)


In [36]:
#array concatenation & splitting
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y],axis=0))
print("-----")
print(x.shape)
print(x.ndim)
print(x[:,np.newaxis])
print(x[:,np.newaxis].shape)
#print(np.concatenate([x, y],axis=1))
print(np.concatenate([x[:,np.newaxis],y[:,np.newaxis]],axis=0))
print("======")
print(np.concatenate([x[:,np.newaxis],y[:,np.newaxis]],axis=1))

[1 2 3 3 2 1]
-----
(3,)
1
[[1]
 [2]
 [3]]
(3, 1)
[[1]
 [2]
 [3]
 [3]
 [2]
 [1]]
[[1 3]
 [2 2]
 [3 1]]


In [37]:
np.concatenate?

In [38]:
print(np.concatenate([x[:,np.newaxis],y[:,np.newaxis]],axis=1))
print(np.hstack([x,y]))
print(np.vstack([x,y]))

[[1 3]
 [2 2]
 [3 1]]
[1 2 3 3 2 1]
[[1 2 3]
 [3 2 1]]


In [39]:
x=[1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3) #also explore np.hsplit, np.vsplit

[1 2 3] [99 99] [3 2 1]


In [40]:
#boolean masks and boolean indexing
arr14 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]); print(arr14)
print(arr14%2==0)
arr14a = arr14%2==0; print(arr14a)
arr14[arr14a]
print(arr14[arr14%2==0])
arr15 = np.array([True,False,True]); print(arr15)
print(arr14[arr15])
print("====")
arr15 = np.array([[1,2],[1],[2]]); print(arr15)
print("====")
print(arr14[[1,2],[1]]) #fancy indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True False  True]
 [False  True False]]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[ True False  True]
[[1 2 3]
 [7 8 9]]
====
[list([1, 2]) list([1]) list([2])]
====
[5 8]


In [41]:
arr16 = np.array([[True,False,True],[True, True,False],[False,False,True]]); print(arr16)
print(arr14[arr16])
print("-----")
print(arr14[~arr14%2==0])
print("-----")
print(arr14[(arr14%2==0) | (arr14%9==0)])
print(arr14[[True,False,True],[2]])
print("-----")
arr17 = np.array([True,False,True])
print(arr14[[True,False,True],[2]])
print("-----")
print(arr14[arr17,[2]])
print("-----1")
print(arr14[[0,2],[2]])
print("-----2")
print(arr14[:2,[2]])

[[ True False  True]
 [ True  True False]
 [False False  True]]
[1 3 4 5 9]
-----
[1 3 5 7 9]
-----
[2 4 6 8 9]
[3 9]
-----
[3 9]
-----
[3 9]
-----1
[3 9]
-----2
[[3]
 [6]]


In [42]:
#fancy indexing (index arrays using lists)
#fancy indexing results into COPYING
x = np.arange(10,1,-1); print(x)
print(x[[3, 3, 1, 8]])
print(x[[3,3,-3,8]])

[10  9  8  7  6  5  4  3  2]
[7 7 9 2]
[7 7 4 2]


In [43]:
arr = np.arange(32).reshape((8, 4)); print(arr)
#here the 1st, 5th, 7th and 2nd rows' 0th, 3rd, 1st and 2nd elements are selected respectively. 
#The result is an one-dimensional array
print("----")
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
----
[ 4 23 29 10]


In [44]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]=0
print(arr)

[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]


In [45]:
#important note the differences and similarities
print(arr); print("----")
a = 1,2; print(type(a))
print(arr[1,2])
print(arr[(1,2)]) #same as previous
print(arr[[1,2]]) #not same as previous but example of fancy indexing

[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]
----
<class 'tuple'>
6
6
[[ 0  5  6  7]
 [ 8  9  0 11]]


In [46]:
import warnings
warnings.filterwarnings("ignore", message="divide by zero encountered") 
warnings.filterwarnings("ignore", message="invalid value encountered")

In [47]:
#UFUNCS
arr12 = np.array([[2,3,4],[3,5,3]]); arr12
print(arr12 + arr12); print("------1")
print(arr12 * arr12)
print(arr12 * 3)
print(arr12 ** 2)
print(arr12)
arr14 = np.eye(3); print(arr14)
print("------2")
print(arr12 * 2)
print("------3")
arr13 = arr12 * 2
print(arr13)
print("------4")
print(arr12.dtype)
print(arr13.dtype)
print("------5")
print(f'arr12 = {arr12}')
print(f'arr13 = {arr13}')
print(f'arr12 > arr13 = {arr12 > arr13}')
arr15 = np.array([[1,3,4],[3,4,3]])
print(f'arr12 <= arr15 = {arr12 <= arr15}')
arr16 = np.arange(15).reshape(3,5); arr16
print("------6")
print(arr16)
print(np.sqrt(arr16))
print("------7")
x = np.random.randn(8); x
print(x)
y = np.random.randn(8); y
print(y)
print("------8")
print(np.maximum(x, y))
np.add(x,y)
arr17 = np.random.randn(7) * 5; arr17
print(f'arr17 = {arr17}')
remainder, whole_part = np.modf(arr17)
print(f'remainder: {remainder} whole_part: {whole_part}')
whole_part
print("------9")
#largest integer smaller than...
np.floor(arr17)
np.ceil(arr17)
arr18 =np.array([np.nan,23,2.3]); arr18
np.isnan(np.nan)
np.isnan(np.inf)
np.isinf(np.inf)
print(np.isnan(arr18))
print("------10")
print(f'np.array([1])/0 = {np.array([1])/0}')
np.dot(arr16,arr16.T)
np.log([-1, 1, 2])
np.mean(arr12) # alternatively arr12.mean()
arr12.sum()
arr12.mean(axis=1)
arr12.mean(axis=0)
print(np.mean(arr12,axis=0))
print("------11")
arr12.cumsum()
arr13 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
#for each col
arr13.cumsum(axis=0)
#for each row
arr13.cumsum(axis=1)
print("------12")
#similarly we have std, var, min, max, argmin, argmax, cumprod
arr14 = np.array([[0, 2, 1], [5, 3, 5], [6, 7, 8]])
print(f'arr14 = {arr14}')
print(arr14.argmax())
print(arr14.argmax(axis=0)) # collapse on the rows i.e. column max
print(arr14.argmax(axis=1)) # collapse on the cols i.e. row max
arr14.max(axis=1)
#boolean arrays
arr15 = np.random.randn(100)
print(f'arr15 = {arr15}')
print((arr15 > 0).sum()) #count of positive values as True has value 1 and False has 0
print((arr15 > 0).any())
print((arr15 > 0).all())

[[ 4  6  8]
 [ 6 10  6]]
------1
[[ 4  9 16]
 [ 9 25  9]]
[[ 6  9 12]
 [ 9 15  9]]
[[ 4  9 16]
 [ 9 25  9]]
[[2 3 4]
 [3 5 3]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
------2
[[ 4  6  8]
 [ 6 10  6]]
------3
[[ 4  6  8]
 [ 6 10  6]]
------4
int64
int64
------5
arr12 = [[2 3 4]
 [3 5 3]]
arr13 = [[ 4  6  8]
 [ 6 10  6]]
arr12 > arr13 = [[False False False]
 [False False False]]
arr12 <= arr15 = [[False  True  True]
 [ True False  True]]
------6
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0.          1.          1.41421356  1.73205081  2.        ]
 [ 2.23606798  2.44948974  2.64575131  2.82842712  3.        ]
 [ 3.16227766  3.31662479  3.46410162  3.60555128  3.74165739]]
------7
[ 1.27078973 -2.081258    0.38891897 -0.52595508  0.32156555  0.36491933
 -0.45002261 -0.27029416]
[-1.29106011  0.25506748 -0.5769377  -0.82411779 -0.59151169  0.60834131
  0.77169656 -0.72917295]
------8
[ 1.27078973  0.25506748  0.38891897 -0.52595508  0.32156555  0.60834131
  0.77169656 -

In [48]:
#sorting (with copy, w/o copy)
print(arr14)
print(arr14.sort(axis=1))
#in place sorting: NO COPY made
#similar to the sort method of python list (as against sorted() available for any python iterable which makes copy)
print(arr14)

[[0 2 1]
 [5 3 5]
 [6 7 8]]
None
[[0 1 2]
 [3 5 5]
 [6 7 8]]


In [49]:
arr15 = np.array([[2,4,3],[3,2,1],[5,2,2]]); print(arr15)
#COPY made
print(np.sort(arr15,axis=1))
print(arr15)

[[2 4 3]
 [3 2 1]
 [5 2 2]]
[[2 3 4]
 [1 2 3]
 [2 2 5]]
[[2 4 3]
 [3 2 1]
 [5 2 2]]


In [50]:
a = np.array([0, 1, 2]); print(a); print(a.shape); print(a.ndim)

[0 1 2]
(3,)
1


In [51]:
M = np.ones((3, 3)); print(M); print(M.shape); print(M.ndim)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
(3, 3)
2


In [52]:
b = M+a; b; print(b); print(b.shape); print(b.ndim)

[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
(3, 3)
2


In [53]:
d = a[np.newaxis,:]; print(d) ; print(d.shape)# Rule 1

[[0 1 2]]
(1, 3)


In [54]:
c = np.vstack([d,d,d]); print(c) ; print(c.shape) # Rule 2

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


In [55]:
M + c

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [56]:
M + 3

array([[ 4.,  4.,  4.],
       [ 4.,  4.,  4.],
       [ 4.,  4.,  4.]])

In [57]:
import numpy as np

In [58]:
####Broadcasting#####
a = np.array([0, 1, 2]); print(a)
M = np.ones((3, 3)); print(M)
b = M+a; print(b)
print(a.shape)
print(M.shape)
print(b.shape)
#the broadcasting steps followed as below:
d = a[np.newaxis,:]; print(f'd={d}') # Rule 1
print(d.shape)
c = np.vstack([d,d,d]); print(c) # Rule 2
print(c.shape)
M + c #same as M+a a(3,) --> d(1,3) --> c(3,3) now c is compatible in shape with M 

[0 1 2]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
(3,)
(3, 3)
(3, 3)
d=[[0 1 2]]
(1, 3)
[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [59]:
#random numbers
np.random.seed(1234)
arr18 = np.random.normal(size=(4, 4)); print(arr18)
print(np.random.binomial(10,0.33,size=15))
print(np.random.normal(5,2,10000).mean())
print(np.random.normal(5,2,10000).std())

[[  4.71435164e-01  -1.19097569e+00   1.43270697e+00  -3.12651896e-01]
 [ -7.20588733e-01   8.87162940e-01   8.59588414e-01  -6.36523504e-01]
 [  1.56963721e-02  -2.24268495e+00   1.15003572e+00   9.91946022e-01]
 [  9.53324128e-01  -2.02125482e+00  -3.34077366e-01   2.11836468e-03]]
[4 5 3 4 1 3 6 4 3 4 3 3 5 3 5]
5.01626562109
1.99205034304


In [60]:
#normal (0,1)
print(np.random.randn(10))
#uniform (0,1)
print(np.random.rand(10))
#uniform
print(np.random.uniform(3,5,10))
#poisson
print(np.random.poisson(4,10))

[ 0.70998653  0.07673163  1.40671103 -0.1882581   0.6041425  -1.05898805
 -0.18200067  0.75309835 -1.58629783 -0.20472974]
[ 0.32733429  0.31205706  0.55506431  0.06348811  0.09068824  0.48554707
  0.93993837  0.256947    0.99234908  0.14905799]
[ 4.49076052  3.06303349  3.42684426  3.25611321  3.22229685  4.85280131
  4.80860069  3.12102794  4.75756056  3.34063864]
[6 4 4 5 4 5 4 1 4 0]


In [61]:
np.random.rand?

In [62]:
######LINEAR ALGEBRA#########
#transpose of array / matrix
arr16 = np.arange(15).reshape(3,5); arr16
arr16.T

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)
np.dot(x,y)
np.dot(y,x)
np.ones(3)
np.dot(x,np.ones(3))

from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
print(X)
mat = X.T.dot(X); print(mat)
print(inv(mat))
print(np.absolute(np.round(mat.dot(inv(mat)))))

[[ 0.62728899 -1.56962766  0.04249242 -0.20745141 -1.71736099]
 [-0.4879239   1.64896042  0.74411823  1.04132083  0.20613372]
 [-0.07152427 -1.36442936  0.38010196  0.09606448  0.36985082]
 [-2.25124685  1.04417784 -0.78196649  0.05686948  0.48445859]
 [-1.468386   -0.20974191 -0.50226351  0.40123683 -0.29992027]]
[[  7.86094675e+00  -3.73430750e+00   2.13431174e+00  -1.36228603e+00
   -1.85454968e+00]
 [ -3.73430750e+00   8.17876793e+00  -6.94643963e-02   1.88687078e+00
    3.09965510e+00]
 [  2.13431174e+00  -6.94643963e-02   1.56373527e+00   5.56568353e-01
   -7.19731254e-03]
 [ -1.36228603e+00   1.88687078e+00   5.56568353e-01   1.30083867e+00
    5.13661682e-01]
 [ -1.85454968e+00   3.09965510e+00  -7.19731254e-03   5.13661682e-01
    3.45326179e+00]]
[[ 1.9118142  -0.35582117 -4.02550312  3.9439944   0.75106548]
 [-0.35582117  0.36484106  0.91162707 -1.15573942 -0.34476077]
 [-4.02550312  0.91162707  9.32790603 -8.8815187  -1.63960733]
 [ 3.9439944  -1.15573942 -8.8815187   9.706

In [63]:
#from numpy.linalg import ....(press tab to see what all you could import from linalg moddule)

In [64]:
from numpy.linalg import det

In [65]:
?det

In [66]:
from numpy.linalg import 

SyntaxError: invalid syntax (<ipython-input-66-77ad9cd14f0c>, line 1)

In [67]:
arr1

array([   6. ,    7.5,  100. ,    0. ,    1. ])

In [68]:
import numpy as np

In [69]:
arr = np.arange(32).reshape((8, 4)); print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [70]:
arr = arr.reshape(2,8,2); arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [71]:
arr[[True,False],[1,1,1],[True,False]]

array([2, 2, 2])

In [72]:
[True,False]*4

[True, False, True, False, True, False, True, False]

In [73]:
arr[:,[True,False]*4,[1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (2,) 

In [74]:
arr[:,[True,False]*4,:]

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]])

In [75]:
arr[:,[True,False]*4]

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]])

In [76]:
arr[:,[True,False]*4,[1]]

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29]])

In [77]:
arr2 = arr[:,[True,False]*4]
arr2.shape

(2, 4, 2)

In [78]:
arr2

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]])

In [79]:
arr2[:,:].shape

(2, 4, 2)

In [80]:
print(arr2[:,:,[1,1]])
#4, <-> 2, -> 1,2 -> 4,2 as below:
x = np.array([1,1])[np.newaxis,:]; x = np.vstack([x,x,x,x]); print(x); print(x.shape)

[[[ 1  1]
  [ 5  5]
  [ 9  9]
  [13 13]]

 [[17 17]
  [21 21]
  [25 25]
  [29 29]]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
(4, 2)


In [81]:
#2, <-> 2,
arr2[:,[True,False]*2,[1,1]]

array([[ 1,  9],
       [17, 25]])

In [82]:
arr2[:,[True,False]*2,[1,1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [83]:
#2, <-> 1, -> 2,
arr2[:,[True,False]*2,[1]]

array([[ 1,  9],
       [17, 25]])

In [84]:
arr2[:,[True,False]*2]

array([[[ 0,  1],
        [ 8,  9]],

       [[16, 17],
        [24, 25]]])

In [85]:
#2, <-> 1, -> 2, as below:
x = np.array([1]); x = np.concatenate([x,x]); print(x); print(x.shape)

[1 1]
(2,)


In [86]:
arr2

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]])

In [87]:
arr2[:,[True,True,True,False],[1]]
#3, <-> 1, -> 3, 

array([[ 1,  5,  9],
       [17, 21, 25]])

In [88]:
arr[:,[True,False]*4][:,:,[1,1]]

array([[[ 1,  1],
        [ 5,  5],
        [ 9,  9],
        [13, 13]],

       [[17, 17],
        [21, 21],
        [25, 25],
        [29, 29]]])

In [89]:
arr[:,[True,False]*4,[1,1,1,1]]

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29]])

In [90]:
arr[:,[True,False]*4,[False,True]]

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29]])

In [91]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [92]:
arr[:,[1],[1,1]]

array([[ 3,  3],
       [19, 19]])

In [93]:
arr[:,[1],[0,1,0,1]]

array([[ 2,  3,  2,  3],
       [18, 19, 18, 19]])

In [94]:
arr[:,[True,False]*4,[[1,1,1,1],[1,1,1,1]]]

array([[[ 1,  5,  9, 13],
        [ 1,  5,  9, 13]],

       [[17, 21, 25, 29],
        [17, 21, 25, 29]]])

In [95]:
#4, <-> 1, -> 4,
arr[:,[True,False]*4,[[1],[1]]]

array([[[ 1,  5,  9, 13],
        [ 1,  5,  9, 13]],

       [[17, 21, 25, 29],
        [17, 21, 25, 29]]])

In [96]:
arr[:,[True,False]*4,[[1],[1],[1]]]

array([[[ 1,  5,  9, 13],
        [ 1,  5,  9, 13],
        [ 1,  5,  9, 13]],

       [[17, 21, 25, 29],
        [17, 21, 25, 29],
        [17, 21, 25, 29]]])

In [97]:
arr[:,[True,False]*4,[1,0,1,0]]

array([[ 1,  4,  9, 12],
       [17, 20, 25, 28]])

In [98]:
arr2[:,[True,False]*2,[1,1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [99]:
arr[:,[True,False]*4]

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]])

In [100]:
arr[:,[True,False]*4]

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]])

In [101]:
arr[:,[True,False]*4,[[1],[0]]]

array([[[ 1,  5,  9, 13],
        [ 0,  4,  8, 12]],

       [[17, 21, 25, 29],
        [16, 20, 24, 28]]])

In [102]:
arr[:,[True,False]*4,[[1],[0]]].shape

(2, 2, 4)

In [103]:
arr[:,[True,False]*4,[[1,0,0,1],[1,0,1,0]]]

array([[[ 1,  4,  8, 13],
        [ 1,  4,  9, 12]],

       [[17, 20, 24, 29],
        [17, 20, 25, 28]]])

In [104]:
arr[:,[True,False]*4,[[1,0,0,1],[1,0,1,0],[1,0,1,0]]]

array([[[ 1,  4,  8, 13],
        [ 1,  4,  9, 12],
        [ 1,  4,  9, 12]],

       [[17, 20, 24, 29],
        [17, 20, 25, 28],
        [17, 20, 25, 28]]])

In [105]:
arr[1,[True,False]*4,[[1],[0]]]

array([[17, 21, 25, 29],
       [16, 20, 24, 28]])

In [106]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [107]:
np.arange(8).reshape(8,1)+np.arange(8).reshape(1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])

In [108]:
arr3 = np.arange(32).reshape((4,2,2,2)); print(arr3)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]]]


In [109]:
arr3[:,[1],[1]]

array([[[ 6,  7]],

       [[14, 15]],

       [[22, 23]],

       [[30, 31]]])

In [110]:
arr3[:,[1,1]]

array([[[[ 4,  5],
         [ 6,  7]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[12, 13],
         [14, 15]],

        [[12, 13],
         [14, 15]]],


       [[[20, 21],
         [22, 23]],

        [[20, 21],
         [22, 23]]],


       [[[28, 29],
         [30, 31]],

        [[28, 29],
         [30, 31]]]])

In [111]:
arr3[:,[1,1],[1]]

array([[[ 6,  7],
        [ 6,  7]],

       [[14, 15],
        [14, 15]],

       [[22, 23],
        [22, 23]],

       [[30, 31],
        [30, 31]]])

In [112]:
arr3[:,[1,1],[1]].shape

(4, 2, 2)

In [113]:
arr3[:,[1,1],[1],[1,1]]

array([[ 7,  7],
       [15, 15],
       [23, 23],
       [31, 31]])

In [114]:
arr2.shape

(2, 4, 2)

In [115]:
arr[[0,1],[0,2,4,6]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (4,) 

In [116]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [117]:
arr.shape

(2, 8, 2)

In [118]:
X = np.arange(12).reshape((3, 4)); X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
row = np.array([0, 1, 2]); col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [120]:
row[:, np.newaxis],col

(array([[0],
        [1],
        [2]]), array([2, 1, 3]))

In [121]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [122]:
arr[[1],[2,4,4,4,6]]

array([[20, 21],
       [24, 25],
       [24, 25],
       [24, 25],
       [28, 29]])

In [123]:
arr[[1],[2,4,4,4,6],[1]]

array([21, 25, 25, 25, 29])

In [124]:
arr[[1],[2,4,4,4,6]]

array([[20, 21],
       [24, 25],
       [24, 25],
       [24, 25],
       [28, 29]])

In [125]:
arr[[0,1],[1,1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [126]:
x=np.array([1,1])
y=np.array([1,1])
z=np.array([1,1])
arr_ind = np.array([x,y,z]); print(arr_ind); print(arr_ind.shape)

[[1 1]
 [1 1]
 [1 1]]
(3, 2)


In [127]:
#print(arr[arr_ind]); 
print(arr[arr_ind].shape)

(3, 2, 8, 2)


In [128]:
print(arr[[1,1],[1,1],[0,1]]); print(arr[[1,1],[1,1],[0,1]].shape); print("1---")
print(arr[[1,1],[1,1]]); print(arr[[1,1],[1,1]].shape);print("2---")
print(arr[[1,1],[1,1],[[0,1]]]); 
print(arr[[1,1],[1,1],[[0,1]]].shape);print("3---")
print(arr[[1,1],[1,1],:]); print(arr[[1,1],[1,1],:].shape); print("4---")
#print(arr[[1,1],[1,1],[0,1,1]]); print(arr[[1,1],[1,1],[0,1,1]].shape)
print(arr[[1,1],[1,1],np.array([0,0])[:,np.newaxis]]); print(arr[[1,1],[1,1],np.array([0,0])].shape)

[18 19]
(2,)
1---
[[18 19]
 [18 19]]
(2, 2)
2---
[[18 19]]
(1, 2)
3---
[[18 19]
 [18 19]]
(2, 2)
4---
[[18 18]
 [18 18]]
(2,)


In [129]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [130]:
arr[[0],[True,False]*4,[1]]

array([ 1,  5,  9, 13])

In [131]:
arr[[0],[True,False]*4,[False,True]]

array([ 1,  5,  9, 13])

In [132]:
arr[[True,False],[0,2,4,6],[False,True]]

array([ 1,  5,  9, 13])

In [133]:
arr[[True,False],[2,2]]

array([[4, 5],
       [4, 5]])

In [134]:
arr[[True,False],[2,2],[False,True]]

array([5, 5])

In [135]:
arr[[True,False],[2,2,4,4]]

array([[4, 5],
       [4, 5],
       [8, 9],
       [8, 9]])

In [136]:
arr[[True,False],[2,2,4,4],[0,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (1,) (4,) (2,) 

In [137]:
#the previous one gave error but this one gave no error as the third dimension integer list must match the 
#number of sub-arrays selected by the third dimension list
#again demonstrated in the next example with 5 integer list
arr[[True,False],[2,2,4,4],[0,1,0,1]]

array([4, 5, 8, 9])

In [138]:
arr[[True,False],[2,2,4,4,5],[0,1,0,1,1]]

array([ 4,  5,  8,  9, 11])

In [139]:
arr30 = np.random.randint(1,10,4*4*3*4).reshape(4,4,3,4); arr30

array([[[[6, 8, 7, 6],
         [1, 1, 9, 1],
         [4, 9, 7, 4]],

        [[8, 7, 2, 9],
         [2, 2, 4, 5],
         [2, 9, 1, 4]],

        [[8, 9, 1, 5],
         [3, 2, 3, 2],
         [4, 5, 7, 6]],

        [[9, 8, 7, 4],
         [4, 1, 2, 6],
         [1, 6, 4, 9]]],


       [[[5, 5, 7, 6],
         [8, 3, 6, 1],
         [8, 9, 3, 5]],

        [[7, 9, 2, 6],
         [6, 2, 4, 2],
         [2, 5, 4, 9]],

        [[6, 3, 5, 6],
         [1, 3, 6, 2],
         [3, 7, 7, 2]],

        [[8, 3, 9, 3],
         [3, 3, 8, 6],
         [6, 4, 7, 9]]],


       [[[1, 7, 6, 7],
         [5, 1, 8, 9],
         [1, 2, 5, 1]],

        [[2, 8, 8, 7],
         [8, 4, 8, 5],
         [6, 2, 2, 3]],

        [[3, 2, 5, 7],
         [5, 8, 3, 4],
         [9, 1, 6, 2]],

        [[5, 1, 7, 6],
         [6, 9, 9, 8],
         [5, 4, 7, 9]]],


       [[[6, 6, 3, 9],
         [3, 3, 7, 6],
         [7, 3, 7, 3]],

        [[4, 5, 3, 8],
         [9, 8, 4, 6],
         [9, 1, 7, 2]],



In [140]:
arr31 = np.random.randint(1,10,3*4).reshape(3,4); arr31

array([[8, 9, 9, 4],
       [4, 6, 2, 5],
       [8, 6, 4, 2]])

In [141]:
print(arr30.shape); print(arr31.shape)

(4, 4, 3, 4)
(3, 4)


In [142]:
arr30+arr31

array([[[[14, 17, 16, 10],
         [ 5,  7, 11,  6],
         [12, 15, 11,  6]],

        [[16, 16, 11, 13],
         [ 6,  8,  6, 10],
         [10, 15,  5,  6]],

        [[16, 18, 10,  9],
         [ 7,  8,  5,  7],
         [12, 11, 11,  8]],

        [[17, 17, 16,  8],
         [ 8,  7,  4, 11],
         [ 9, 12,  8, 11]]],


       [[[13, 14, 16, 10],
         [12,  9,  8,  6],
         [16, 15,  7,  7]],

        [[15, 18, 11, 10],
         [10,  8,  6,  7],
         [10, 11,  8, 11]],

        [[14, 12, 14, 10],
         [ 5,  9,  8,  7],
         [11, 13, 11,  4]],

        [[16, 12, 18,  7],
         [ 7,  9, 10, 11],
         [14, 10, 11, 11]]],


       [[[ 9, 16, 15, 11],
         [ 9,  7, 10, 14],
         [ 9,  8,  9,  3]],

        [[10, 17, 17, 11],
         [12, 10, 10, 10],
         [14,  8,  6,  5]],

        [[11, 11, 14, 11],
         [ 9, 14,  5,  9],
         [17,  7, 10,  4]],

        [[13, 10, 16, 10],
         [10, 15, 11, 13],
         [13, 10, 11, 11]]],


In [143]:
temp1 = arr31[np.newaxis,:,:]; temp1.shape

(1, 3, 4)

In [144]:
temp1

array([[[8, 9, 9, 4],
        [4, 6, 2, 5],
        [8, 6, 4, 2]]])

In [145]:
temp2 = np.vstack([temp1]*4); temp2.shape

(4, 3, 4)

In [146]:
temp2

array([[[8, 9, 9, 4],
        [4, 6, 2, 5],
        [8, 6, 4, 2]],

       [[8, 9, 9, 4],
        [4, 6, 2, 5],
        [8, 6, 4, 2]],

       [[8, 9, 9, 4],
        [4, 6, 2, 5],
        [8, 6, 4, 2]],

       [[8, 9, 9, 4],
        [4, 6, 2, 5],
        [8, 6, 4, 2]]])

In [147]:
temp3 = temp2[np.newaxis,:,:,:]; temp3.shape

(1, 4, 3, 4)

In [148]:
temp4 = np.vstack([temp3]*4); temp4.shape

(4, 4, 3, 4)

In [149]:
arr30.shape

(4, 4, 3, 4)

In [150]:
# verify
np.sum((arr30+temp4 != arr30+arr31).reshape(4*4*3*4))

0

In [151]:
import numpy as np

In [152]:
x = np.array(1234678901234567890); print(x)
print(x.dtype)
x = np.array(1234678901234567890,dtype=np.int0); print(x)
print(x.dtype)
x = np.array(1234678901234567890,dtype=np.int8); print(x)
print(x.dtype)
x = np.array(1234678901234567890,dtype=np.int16); print(x)
print(x.dtype)
x = np.array(1234678901234567890,dtype=np.int32); print(x)
print(x.dtype)
x = np.array(1234678901234567890,dtype=np.int64); print(x)
print(x.dtype)

1234678901234567890
int64
1234678901234567890
int64
-46
int8
-29998
int16
1203866322
int32
1234678901234567890
int64


In [153]:
x = np.array([-130],dtype=np.int8); print(x)
x = np.array([-129],dtype=np.int8); print(x)
x = np.array([-128],dtype=np.int8); print(x) # correct
x = np.array([-127],dtype=np.int8); print(x) # correct
x = np.array([-126],dtype=np.int8); print(x) # correct
print('--------------------')
x = np.array([130],dtype=np.int8); print(x)
x = np.array([129],dtype=np.int8); print(x)
x = np.array([128],dtype=np.int8); print(x)
x = np.array([127],dtype=np.int8); print(x) # correct
x = np.array([126],dtype=np.int8); print(x) # correct

[126]
[127]
[-128]
[-127]
[-126]
--------------------
[-126]
[-127]
[-128]
[127]
[126]


In [154]:
x = np.array([128],dtype=np.int8); x

array([-128], dtype=int8)

In [155]:
print(np.binary_repr(128,width=8))  # this is same as -128 representation w/o the minus symbol
print(np.binary_repr(-128,width=8))
print(np.binary_repr(-128))
# 2's complement of 128: invert the digits and add 1
# 01111111 + 1 = 10000000 = +128 covering all 8 digits but since MSB is sign so it represents -128

10000000
10000000
-10000000


In [156]:
# similarly for -127
print(np.array(-127,dtype=np.int8))
print(np.binary_repr(-127,width=8))  # take bin repr of +127 as in next line, then invert the digits and add 1
print(np.binary_repr(127,width=8))  # bin repr of +127

-127
10000001
01111111


In [157]:
# similarly for -126
print(np.array(-126,dtype=np.int8))
print(np.binary_repr(-126,width=8))  # take bin repr of +126 as in next line, then invert the digits and add 1
print(np.binary_repr(126,width=8))  # bin repr of +126

-126
10000010
01111110


In [158]:
# similarly for -129
print(np.array(-129,dtype=np.int8))
print(np.binary_repr(-129,width=9))  # take bin repr of +129 as in next line, then invert the digits and add 1
print(np.binary_repr(129,width=9))   # bin repr of +129 requires 9 digits if we need an extra bit for sign
print(np.binary_repr(127,width=9))   # this is what 2nd print statement gives w/o the 9th left most bit (MSB) so overflow 

127
101111111
010000001
001111111


In [159]:
# similarly for -130
print(np.array(-130,dtype=np.int8))
print(np.binary_repr(-130,width=9))  # take bin repr of +130 as in next line, then invert the digits and add 1
print(np.binary_repr(130,width=9))   # bin repr of +130 requires 9 digits if we need an extra bit for sign
print(np.binary_repr(126,width=9))   # this is what 2nd print statement gives w/o the 9th left most bit (MSB) so overflow 

126
101111110
010000010
001111110


In [160]:
# similarly for 130
print(np.array(130,dtype=np.int8))
print(np.binary_repr(130,width=9))  # take bin repr of +130 as in next line and no further changes for 2's complement
print(np.binary_repr(130,width=9))   # bin repr of +130 requires 9 digits if we need an extra bit for sign
print(np.binary_repr(-126,width=8))   # this is what 2nd print statement gives w/o the 9th left most bit (MSB) so overflow 

-126
010000010
010000010
10000010


In [161]:
# similarly for 129
print(np.array(129,dtype=np.int8))
print(np.binary_repr(129,width=9))  # take bin repr of +129 as in next line and no further changes for 2's complement
print(np.binary_repr(129,width=9))   # bin repr of +129 requires 9 digits if we need an extra bit for sign
print(np.binary_repr(-127,width=8))   # this is what 2nd print statement gives w/o the 9th left most bit (MSB) so overflow 

-127
010000001
010000001
10000001


In [162]:
# similarly for 128
print(np.array(128,dtype=np.int8))
print(np.binary_repr(128,width=9))  # take bin repr of +128 as in next line and no further changes for 2's complement
print(np.binary_repr(128,width=9))   # bin repr of +128 requires 9 digits if we need an extra bit for sign
print(np.binary_repr(-128,width=8))   # this is what 2nd print statement gives w/o the 9th left most bit (MSB) so overflow 

-128
010000000
010000000
10000000


In [163]:
print(np.iinfo(np.int))
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [164]:
print(np.finfo(np.float))
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))
print(np.finfo(np.float128))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resoluti

In [165]:
print(np.iinfo(np.long))
print(np.iinfo(np.longlong))
print(np.finfo(np.longdouble))
print(np.finfo(np.longfloat))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float128
---------------------------------------------------------------
precision =  18   resolution = 1e-18
machep =    -63   eps =        1.08420217249e-19
negep =     -64   epsneg =     5.42101086243e-20
minexp = -16382   tiny =       3.36210314311e-4932
maxexp =  16384   max =        1.18973149536e+4932
nexp =       15   min =        -max
---------------------------------------------------------------

Machine parameters for float128
---------------------------------------------------------------
precision =  18   resolution = 1e-18
machep =   

In [166]:
# notice the 15 0's in the decimal part - float64 precision = 15
1 + np.finfo(np.float64).eps

1.0000000000000002

In [167]:
# here if we add something less than 0000000000000002 it amounts to actual difference
print(1 + np.finfo(np.float64).eps == 1 + np.finfo(np.float64).eps+ .00000000000000001)
print(1 + np.finfo(np.float64).eps == 1 + np.finfo(np.float64).eps+ .0000000000000001)
print(1 + np.finfo(np.float64).eps == 1 + np.finfo(np.float64).eps+ .0000000000000002)
print(1 + np.finfo(np.float64).eps == 1 + np.finfo(np.float64).eps+ .0000000000000003)

True
True
False
False


In [168]:
from numpy.linalg import inv
def f1(mat):
    if mat.ndim != 2:
        raise Exception('you need to provide a 2D matrix')
    if mat.shape[0]==mat.shape[1]:
        if np.sum( (np.absolute(np.round(np.dot(mat,inv(mat)))) != 
                    np.eye(mat.shape[0])).reshape(mat.shape[0]*mat.shape[1]))==0:
            return True
    return False                

In [169]:
from numpy.linalg import inv, LinAlgError
def f2(mat):
    try:
        if np.sum( (np.absolute(np.round(np.dot(mat,inv(mat)))) != 
                    np.eye(mat.shape[0])).reshape(mat.shape[0]*mat.shape[1]))==0:
            return True
    except LinAlgError:
        print('you need to provide a 2D square matrix')

In [170]:
mat1 = np.random.randint(1,10,25).reshape(5,5); mat1

array([[5, 1, 8, 1, 3],
       [5, 5, 2, 3, 2],
       [5, 4, 5, 4, 3],
       [8, 2, 3, 1, 6],
       [2, 7, 2, 5, 8]])

In [171]:
f1(mat1)

True

In [172]:
f1(np.random.randint(1,10,25))

Exception: you need to provide a 2D matrix

In [ ]:
f2(np.random.randint(1,10,25))

In [ ]:
f2(np.random.randint(1,10,12).reshape(4,3))