In [2]:
"""
-----------------------------------------------------------------------------
Assignment-2: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState

from typing import Tuple

np.random.seed(42)# To reproduce the random numbers


# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.

In [3]:
n = 10
l = 9
x = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#

# np.random.seed(42)# for reproduce the random numbers
x = np.random.randint(-l, l, n)

#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x: {}' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x: [-3  5  1 -2 -3  1  1 -6 -2 -7]
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).




In [4]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st vector
        - y: 2nd vector
       
    Output:
        - val: Dot product between x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    if x.shape[0] == y.shape[0]:
        val = 0
        for i in range(x.shape[0]):
            val += x[i] * y[i]
    else:
        raise ValueError('Please check the dimention of the vectors!')
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
x = np.random.randint(-l, l, n).astype(float)
y = np.random.randint(-l, l, n).astype(float)

print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: [-8.  2. -4. -8. -9.  2.  2.  7.  0.  6.]
and 
y: [ 5.  5.  2. -7. -5. -3. -1. -3.  8. -6.]
----------------------------------------------------------------------
The dot product between x and y is: -2.0
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.

In [5]:
m = 3
n = 5
l = 9
A = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#

# np.random.seed(42)# for reproduce the random numbers
A = np.random.randint(-l, l, [m, n])

#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)




A random matrix of size 3x5 A:
[[ 4  8 -1 -8  5]
 [-3  2 -2  5 -7]
 [ 4  7 -6  8 -2]]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).




In [6]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st matrix
        - y: 2nd matrix
       
    Output:
        - val: multiplication x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    if x.shape[1] == y.shape[0]:
        val = np.zeros((x.shape[0], y.shape[1]))
        for i in range(x.shape[0]):
            for j in range(y.shape[1]):
                for k in range(x.shape[1]):
                    val[i, j] += x[i, k] * y[k, j]
    else:
        raise ValueError('Please check the dimention of the matrix!')
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
A = np.random.randint(-l, l, [m, n]).astype(float)
B = np.random.randint(-l, l, [n, m]).astype(float)

print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = matrix_multiplication(A, B)
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A, B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)


Two random matrices are:
A: 
[[-6. -8. -4.  0. -6.]
 [ 8.  2. -8.  0. -6.]
 [ 4.  6.  5. -2.  4.]]
and
B: 
[[-2.  6.  3.]
 [ 8.  5.  3.]
 [-1.  5.  3.]
 [-9. -3. -1.]
 [-9.  2. -2.]]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[[   6. -108.  -42.]
 [  62.    6.   18.]
 [  17.   93.   39.]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
[[   6. -108.  -42.]
 [  62.    6.   18.]
 [  17.   93.   39.]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
[[   6. -108.  -42.]
 [  62.    6.   18.]
 [  17.   93.   39.]]
----------------------------------------------------------------------


# Implement elementary row operations and check your script with a random example.

In [16]:
def elementary_ops_interchange_rows(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->np.array:
    """
    Elementary row operation: interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    Temp = np.copy(A[ith_row,:])
    A[ith_row,:] = A[jth_row,:]
    A[jth_row,:] = Temp
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_row(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    A[ith_row,:] *= scalar_val
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_row(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    A[ith_row,:] += scalar_val * A[jth_row,:]
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_interchange_rows_mult(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->Tuple[np.array, np.array]:
    """
    Elementary row operation (using pre-multiplication by elementary matrix): interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    I = np.eye(A.shape[0])
    I = elementary_ops_interchange_rows(I, ith_row, jth_row)
    A = matrix_multiplication(I, A)
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


def elementary_ops_scale_row_mult(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary row operation (using pre-multiplication by elementary matrix): Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    I = np.eye(A.shape[0])
    I = elementary_ops_scale_row(I, ith_row, scalar_val)
    A = matrix_multiplication(I, A)
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I

def elementary_ops_change_row_mult(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary row operation (using pre-multiplication by elementary matrix): Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    I = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    I = np.eye(A.shape[0])
    I = elementary_ops_change_row(I, ith_row, jth_row, scalar_val)
    A = matrix_multiplication(I, A)
    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = np.random.randint(-l, l, [m, n]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_rows(A.copy(), i, j)
print('Elementary row operation: interchange {}-th and {}-th rows on A: \n{}\nis: \n{}' .format(i, j, A, E_ij))
print('-'*70)

E_i = elementary_ops_scale_row(A.copy(), i, scalar)
print('Elementary row operation: Scaling {}-th row  with the {} value on A: \n{}\nis: \n{}' .format(i, scalar, A, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_row(A.copy(), i, j, scalar)
print('Elementary row operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}\nis: \n{}' .format(i, i, i, scalar, j, A, E_ij_scalar))
print('-'*70)

E_ij, I_ij = elementary_ops_interchange_rows_mult(A.copy(), i, j)
print('Elementary row operation (multiplication): interchange {}-th and {}-th rows on A: \n{}\nis: \n{}\nand I_ij: \n{}' .format(i, j, A, E_ij, I_ij))
print('-'*70)

E_i, I_i = elementary_ops_scale_row_mult(A.copy(), i, scalar)
print('Elementary row operation(multiplication): Scaling {}-th row  with the {} value on A: \n{}\nis: \n{}\nand I_i: \n{}' .format(i, scalar, A, E_i, I_i))
print('-'*70)

E_ij_scalar, I_ij_scalar = elementary_ops_change_row_mult(A.copy(), i, j, scalar)
print('Elementary row operation(multiplication): Change {}-th based on {}<-{} + {}*{} on A: \n{}\nis: \n{}\nand I_ij(scale): \n{}' .format(i, i, i, scalar, j, A, E_ij_scalar, I_ij_scalar))
print('-'*70)




A random matrices A:
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
----------------------------------------------------------------------
Elementary row operation: interchange 1-th and 2-th rows on A: 
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
is: 
[[-3.  5.  1. -2. -3.]
 [-8.  2. -4. -8. -9.]
 [ 1.  1. -6. -2. -7.]]
----------------------------------------------------------------------
Elementary row operation: Scaling 1-th row  with the 3 value on A: 
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
is: 
[[ -3.   5.   1.  -2.  -3.]
 [  3.   3. -18.  -6. -21.]
 [ -8.   2.  -4.  -8.  -9.]]
----------------------------------------------------------------------
Elementary row operation: Change 1-th based on 1<-1 + 3*2 on A: 
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
is: 
[[ -3.   5.   1.  -2.  -3.]
 [-23.   7. -18. -26. -34.]
 [ -8.   2.  -4.  -8.  -9.]]
----------------------------------

# Implement elementary column operations and check your script with random example

In [17]:
def elementary_ops_interchange_cols(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    Temp = np.copy(A[:, ith_col])
    A[:, ith_col] = A[:, jth_col]
    A[:, jth_col] = Temp
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_col(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    A[:, ith_col] *= scalar_val
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_col(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    A[:, ith_col] += scalar_val * A[:, jth_col]
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_interchange_cols_mult(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    I = np.eye(A.shape[1])
#     I = elementary_ops_interchange_cols(I, ith_col, jth_col)
    I = elementary_ops_interchange_rows(I, ith_col, jth_col)
    A = matrix_multiplication(A, I)
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


def elementary_ops_scale_col_mult(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    I = np.eye(A.shape[1])
#     I = elementary_ops_scale_col(I, ith_col, scalar_val)
    I = elementary_ops_scale_row(I, ith_col, scalar_val)
    A = matrix_multiplication(A, I)
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I

def elementary_ops_change_col_mult(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    I = np.eye(A.shape[1])
#     I = elementary_ops_change_col(I, ith_col, jth_col, scalar_val)
    I = elementary_ops_change_row(I, jth_col, ith_col, scalar_val)# Please note that i&j has interchanged. As Eij and Ei(alpha) is symmetric but [Eij(alpha)]^T = Eji(alpha)
    A = matrix_multiplication(A, I)
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = np.random.randint(-l, l, [m, n]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_cols(np.copy(A), i, j)
print('Elementary col operation: interchange {}-th and {}-th cols on A: \n{}' .format(i, j, E_ij))
print('-'*70)

E_i = elementary_ops_scale_col(np.copy(A), i, scalar)
print('Elementary col operation: Scaling {}-th col  with the {} value on A: \n{}' .format(i, scalar, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_col(np.copy(A), i, j, scalar)
print('Elementary col operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}' .format(i, i, i, scalar, j, E_ij_scalar))
print('-'*70)

E_ij, I_ij = elementary_ops_interchange_cols_mult(np.copy(A), i, j)
print('Elementary col operation (multiplication): interchange {}-th and {}-th cols on A: \n{}\nis: \n{}\nand I_ij: \n{}' .format(i, j, A, E_ij, I_ij))
print('-'*70)

E_i, I_i = elementary_ops_scale_col_mult(np.copy(A), i, scalar)
print('Elementary col operation (multiplication): Scaling {}-th col  with the {} value on A: \n{}\nis: \n{}\nand I_i: \n{}' .format(i, scalar, A, E_i, I_i))
print('-'*70)

E_ij_scalar, I_ij_scalar = elementary_ops_change_col_mult(np.copy(A), i, j, scalar)
print('Elementary col operation (multiplication): Change {}-th based on {}<-{} + {}*{} on A: \n{}\nis: \n{}\nand I_ij_scalar: \n{}' .format(i, i, i, scalar, j, A, E_ij_scalar, I_ij_scalar))
print('-'*70)


A random matrices A:
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
----------------------------------------------------------------------
Elementary col operation: interchange 1-th and 2-th cols on A: 
[[-3.  1.  5. -2. -3.]
 [ 1. -6.  1. -2. -7.]
 [-8. -4.  2. -8. -9.]]
----------------------------------------------------------------------
Elementary col operation: Scaling 1-th col  with the 3 value on A: 
[[-3. 15.  1. -2. -3.]
 [ 1.  3. -6. -2. -7.]
 [-8.  6. -4. -8. -9.]]
----------------------------------------------------------------------
Elementary col operation: Change 1-th based on 1<-1 + 3*2 on A: 
[[ -3.   8.   1.  -2.  -3.]
 [  1. -17.  -6.  -2.  -7.]
 [ -8. -10.  -4.  -8.  -9.]]
----------------------------------------------------------------------
Elementary col operation (multiplication): interchange 1-th and 2-th cols on A: 
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
is: 
[[-3.  1.  5. -2. -3.]
 [ 1. -6.  1. -2. -7.]
 

# Implement row and column sweep out and check your script with random example

In [22]:
def sweep_out_row(
    A: np.array,
    ith_row: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th row based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_row: row to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant row sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    A = elementary_ops_scale_col(A, pivot_element[1], 1./A[pivot_element[0], pivot_element[1]])
    for j in range(A.shape[1]):
        if(j != pivot_element[1]):
            A = elementary_ops_change_col(A, j, pivot_element[1], -A[ith_row, j])
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A
    
def sweep_out_row_mult(
    A: np.array,
    ith_row: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th row based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_row: row to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant row sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    E_ops = np.eye(A.shape[1])
    A, C_i = elementary_ops_scale_col_mult(A, pivot_element[1], 1./A[pivot_element[0], pivot_element[1]])
    E_ops = C_i.copy()
    for j in range(A.shape[1]):
        if(j != pivot_element[1]):
            A, C_ij_scale = elementary_ops_change_col_mult(A, j, pivot_element[1], -A[ith_row, j])
            E_ops = matrix_multiplication(E_ops, C_ij_scale)
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A, E_ops
    
    
def sweep_out_col(
    A: np.array,
    ith_col: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th column based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_col: column to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant column sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    A = elementary_ops_scale_row(A, pivot_element[0], 1./A[pivot_element[0], pivot_element[1]])
    for i in range(A.shape[0]):
        if(i != pivot_element[0]):
            A = elementary_ops_change_row(A, i, pivot_element[0], -A[i, ith_col])
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A

def sweep_out_col_mult(
    A: np.array,
    ith_col: int,
    pivot_element: Tuple[int, int]
)->Tuple[np.array, np.array]:
    """
    Sweep out a i-th column based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_col: column to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant column sweep out matrix
        - E_ops: Product of all the elementary operations
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    E_ops = np.eye(A.shape[0])
    A, I_i = elementary_ops_scale_row_mult(A, pivot_element[0], 1./A[pivot_element[0], pivot_element[1]])
    E_ops = I_i.copy()
    for i in range(A.shape[0]):
        if(i != pivot_element[0]):
            A, I_ij_scale = elementary_ops_change_row_mult(A, i, pivot_element[0], -A[i, ith_col])
            E_ops = matrix_multiplication(I_ij_scale, E_ops)
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A, E_ops




np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = np.random.randint(-l, l, [m, n]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = sweep_out_row(np.copy(A), i, (i, j))
print('{}-th row sweep out based on ({}, {}) as pivot on A: \n{}\nis : \n{}' .format(i, i, j, A, E_ij))
print('-'*70)

E_ij, E_ops = sweep_out_row_mult(np.copy(A), i, (i, j))
print('{}-th row sweep out (multiplication) based on ({}, {}) as pivot on A: \n{}\nis: \n{}\nand product of all the elementary operations E_ops: \n{}' .format(i, i, j, A, E_ij, E_ops))
print('-'*70)

E_ij = sweep_out_col(np.copy(A), j, (i, j))
print('{}-th col sweep out based on ({}, {}) as pivot on A: \n{}' .format(j, i, j, E_ij))
print('-'*70)

E_ij, E_ops = sweep_out_col_mult(np.copy(A), j, (i, j))
print('{}-th col sweep out (multiplication) based on ({}, {}) as pivot on A: \n{}\n is : \n{}\nand product of all the elementary operations E_ops: \n{}' .format(j, i, j, A, E_ij, E_ops))
print('-'*70)



A random matrices A:
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
----------------------------------------------------------------------
1-th row sweep out based on (1, 2) as pivot on A: 
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
is : 
[[-2.83333333  5.16666667 -0.16666667 -2.33333333 -4.16666667]
 [ 0.          0.          1.          0.          0.        ]
 [-8.66666667  1.33333333  0.66666667 -6.66666667 -4.33333333]]
----------------------------------------------------------------------
1-th row sweep out (multiplication) based on (1, 2) as pivot on A: 
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]]
is: 
[[-2.83333333  5.16666667 -0.16666667 -2.33333333 -4.16666667]
 [ 0.          0.          1.          0.          0.        ]
 [-8.66666667  1.33333333  0.66666667 -6.66666667 -4.33333333]]
and product of all the elementary operations E_ops: 
[[ 1.          0.          0.          0.          0.        ]
 

# Implement reduced echelon form of a matrix $A$

In [23]:
def reduced_echelon_form(
    A: np.array
)-> np.array:
    """Reduction to echelon form of a matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Echelon form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    num_rows, num_cols = A.shape
    i = 0
    j = 0
    l = 0
    while((l < num_rows) and (j  < num_cols)):
        if(A[i, j] != 0):
            A = elementary_ops_interchange_rows(A, l, i)
            A = sweep_out_col(A, j, (l, j))
            l += 1
        else:
            if(i < num_rows - 1):
                i += 1
            else:
                j += 1
                i = l
                        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A
        
    
np.random.seed(42)# for reproduce the random numbers
m = 4
n = 5
A = np.random.randint(-l, l, [m, n]).astype(float)
A = np.array([
    [0, 0, 0, 0, 5],
    [0, 2, -1, 3, -2],
    [0, -4, 2, -6, 4],
    [0, 6, -3, 8, 1]
]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)

EF_A = reduced_echelon_form(A) 
print('The reduced echelon form of A:\n{} ' .format(np.round(EF_A, 3)))
print('-'*70)
        
    

A random matrices A:
[[ 0.  0.  0.  0.  5.]
 [ 0.  2. -1.  3. -2.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]]
----------------------------------------------------------------------
The reduced echelon form of A:
[[ 0.   1.  -0.5  0.   0. ]
 [ 0.   0.   0.   1.   0. ]
 [ 0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   0.   0. ]] 
----------------------------------------------------------------------


# Implement reduction to upper triangular form of a matrix $A$

In [24]:

def reduced_upper_triangular_form(
    A: np.array
)-> np.array:
    """Reduction to upper triangular form of a square matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Upper triangular form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    num_rows, num_cols = A.shape
    i = 0
    j = 0
    while(j < num_cols - 1):
        if(A[i, j] != 0):
            A = elementary_ops_interchange_rows(A, i, j)
            for k in range(j+1, num_cols, 1):
                A[k,:] -= (A[k, j]/A[j, j])*A[j, :]
        else:
            if(i < num_rows - 1):
                i += 1
                
        j += 1
        i = j
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

np.random.seed(42)# for reproduce the random numbers
n = 5
A = np.random.randint(-l, l, [n, n]).astype(float)
print('A random matrices A:\n{}' .format(A))
print('-'*70)

UT_A = reduced_upper_triangular_form(A)        
print('The reduced upper triangular form of A:\n{} ' .format(np.round(UT_A, 3)))
print('-'*70)      






A random matrices A:
[[-3.  5.  1. -2. -3.]
 [ 1.  1. -6. -2. -7.]
 [-8.  2. -4. -8. -9.]
 [ 2.  2.  7.  0.  6.]
 [ 5.  5.  2. -7. -5.]]
----------------------------------------------------------------------
The reduced upper triangular form of A:
[[ -3.      5.      1.     -2.     -3.   ]
 [  0.      2.667  -5.667  -2.667  -8.   ]
 [  0.      0.    -30.75  -14.    -35.   ]
 [  0.      0.      0.     -4.65   -1.626]
 [  0.     -0.      0.      0.     -2.378]] 
----------------------------------------------------------------------
