In [1]:
"""
-----------------------------------------------------------------------------
Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState

from typing import Tuple

np.random.seed(42)# To reproduce the random numbers


# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.

In [2]:
n = 10
l = 9
x = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#


#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x: {}' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x: []
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).




In [4]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st vector
        - y: 2nd vector
       
    Output:
        - val: Dot product between x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
x = []
y = []

print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: []
and 
y: []
----------------------------------------------------------------------
The dot product between x and y is: []
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.

In [5]:
m = 3
n = 5
l = 9
A = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#

#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)



A random matrix of size 3x5 A:
[]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).




In [6]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st matrix
        - y: 2nd matrix
       
    Output:
        - val: multiplication x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
A = []
B = []

print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = matrix_multiplication(A, B)
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A, B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)


Two random matrices are:
A: 
[]
and
B: 
[]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
0.0
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
False
----------------------------------------------------------------------


# Implement elementary row operations and check your script with a random example.

In [7]:
def elementary_ops_interchange_rows(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->np.array:
    """
    Elementary row operation: interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_row(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_row(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = []

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_rows(A, i, j)
print('Elementary row operation: interchange {}-th and {}-th rows on A: \n{}' .format(i, j, E_ij))
print('-'*70)

E_i = elementary_ops_scale_row(A, i, scalar)
print('Elementary row operation: Scaling {}-th row  with the {} value on A: \n{}' .format(i, scalar, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_row(A, i, j, scalar)
print('Elementary row operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}' .format(i, i, i, scalar, j, E_ij_scalar))
print('-'*70)



A random matrices A:
[]
----------------------------------------------------------------------
Elementary row operation: interchange 1-th and 2-th rows on A: 
[]
----------------------------------------------------------------------
Elementary row operation: Scaling 1-th row  with the 3 value on A: 
[]
----------------------------------------------------------------------
Elementary row operation: Change 1-th based on 1<-1 + 3*2 on A: 
[]
----------------------------------------------------------------------


# Implement elementary column operations and check your script with random example

In [8]:
def elementary_ops_interchange_cols(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_col(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_col(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#

            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = []

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_cols(np.copy(A), i, j)
print('Elementary col operation: interchange {}-th and {}-th cols on A: \n{}' .format(i, j, E_ij))
print('-'*70)

E_i = elementary_ops_scale_col(np.copy(A), i, scalar)
print('Elementary col operation: Scaling {}-th col  with the {} value on A: \n{}' .format(i, scalar, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_col(np.copy(A), i, j, scalar)
print('Elementary col operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}' .format(i, i, i, scalar, j, E_ij_scalar))
print('-'*70)

A random matrices A:
[]
----------------------------------------------------------------------
Elementary col operation: interchange 1-th and 2-th cols on A: 
[]
----------------------------------------------------------------------
Elementary col operation: Scaling 1-th col  with the 3 value on A: 
[]
----------------------------------------------------------------------
Elementary col operation: Change 1-th based on 1<-1 + 3*2 on A: 
[]
----------------------------------------------------------------------


# Implement row and column sweep out and check your script with random example

In [9]:
def sweep_out_row(
    A: np.array,
    ith_row: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th row based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_row: row to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant row sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A
    
    
def sweep_out_col(
    A: np.array,
    ith_col: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th column based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_col: column to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant column sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A



np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = []

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = sweep_out_row(np.copy(A), i, (i, j))
print('{}-th row sweep out based on ({}, {}) as pivot on A: \n{}' .format(i, i, j, E_ij))
print('-'*70)

E_ij = sweep_out_col(np.copy(A), j, (i, j))
print('{}-th col sweep out based on ({}, {}) as pivot on A: \n{}' .format(j, i, j, E_ij))
print('-'*70)


A random matrices A:
[]
----------------------------------------------------------------------
1-th row sweep out based on (1, 2) as pivot on A: 
[]
----------------------------------------------------------------------
2-th col sweep out based on (1, 2) as pivot on A: 
[]
----------------------------------------------------------------------


# Implement reduced echelon form of a matrix $A$

In [10]:
def reduced_echelon_form(
    A: np.array
)-> np.array:
    """Reduction to echelon form of a matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Echelon form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
                        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A
        
    
np.random.seed(42)# for reproduce the random numbers
m = 4
n = 5
A = []
A = np.array([
    [0, 0, 0, 0, 5],
    [0, 2, -1, 3, -2],
    [0, -4, 2, -6, 4],
    [0, 6, -3, 8, 1]
]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)

EF_A = reduced_echelon_form(A) 
print('The reduced echelon form of A:\n{} ' .format(np.round(EF_A, 3)))
print('-'*70)
        
    

A random matrices A:
[[ 0.  0.  0.  0.  5.]
 [ 0.  2. -1.  3. -2.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]]
----------------------------------------------------------------------
The reduced echelon form of A:
[[ 0.  0.  0.  0.  5.]
 [ 0.  2. -1.  3. -2.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]] 
----------------------------------------------------------------------


# Implement reduction to upper triangular form of a matrix $A$

In [11]:

def reduced_upper_triangular_form(
    A: np.array
)-> np.array:
    """Reduction to upper triangular form of a square matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Upper triangular form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

np.random.seed(42)# for reproduce the random numbers
n = 5
A = []
print('A random matrices A:\n{}' .format(A))
print('-'*70)

UT_A = reduced_upper_triangular_form(A)        
print('The reduced upper triangular form of A:\n{} ' .format(np.round(UT_A, 3)))
print('-'*70)      






A random matrices A:
[]
----------------------------------------------------------------------
The reduced upper triangular form of A:
[] 
----------------------------------------------------------------------
